= Ближайшие задачи

== Скролл в Меню

* [ ] Если Пользователь скроллит, когда у него мышка на списке, то скролить список
* [ ] Если Пользователь скроллит, когда у него мышка на описании, то скролить описание
* [ ] При переходе в ПодМеню и обратно скролл должен быть на уровне первая строка = выбранный элемент
* [ ] При переходе от итема к итему, скролл описания должен сбрасываться
* [ ] Если пользователь выбирает предыдущий или следующий элемент списка меню, а элемент вне отображения, то переместить отображение на него
** Если элемент ниже отображаемых, то должен быть первым снизу
** Если элемент выше отображаемых, то должен быть первым сверху
* [ ] Сделать ползунок для обознчания скрола

== Ресайз

* [ ] При ресайзе терминала необходимо редактировать  отображаемый контент
** Если высота увеличилась, то:
*** То сначала добавляются элементы снизу спика
*** Как только список до конца отображен снизу, тогда начинает дополнять элементы сверху списка
** Если высота уменьшилась, то первый элемнт должен сохранять свое положение